title: Les Baroqueurs du XVIIIème
description: Ensemble de flutiste à bec

url: https://www.baroqueurs.fr
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
future: true

navigation:
  - title: Accueil
    url: /index.html
  - title: L'Ensemble
    url: /ensemble
  - title: Calendrier des Concerts
    url: /calendrier
  - title: Extraits
    url: /extraits
  - title: Photos
    url: /photos
  - title: Contact
    url: /contact

collections:
  musiciens:
    output: false
  concerts:
    output: true
  extraits:
    output: false

social:
  facebook: consort.baroqueurs.5
  email: contact@baroqueurs.fr
