---
title: Les Baroqueurs du XVIIIème
timezone: Europe/Paris
collections:
  concerts:
    title: Concerts
    output: true
  musiciens:
    title: Musiciens
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Ensemble de flutiste à bec
url: https://www.baroqueurs.fr
baseurl: 
paginate_path: blog/page:num/
permalink: blog/:title/
markdown: kramdown
highlighter: rouge
future: true
social:
  facebook: consort.baroqueurs.5
  email: contact@baroqueurs.fr
plugins:
- jekyll-menus